# Amazon Q pre block. Keep at the top of this file.
if [[ -f "${HOME}/.config/enable-amazon-q" ]]; then
    # echo "\n<< start zprofile >>\n"
    echo -n "zprofile 🌞 🛫.."
    if [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zprofile.pre.zsh" ]]; then
        builtin source "${HOME}/Library/Application Support/amazon-q/shell/zprofile.pre.zsh"
        echo "..🛬 🌞 zprofile"
    fi
fi

#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='lvim'
export VISUAL='code'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -s "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi


# Setting PATH for Python 3.10
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH

# Amazon Q post block. Keep at the bottom of this file.
if [[ -f "${HOME}/.config/enable-amazon-q" ]]; then
    echo -n "zprofile 🪙 🛫.."
    if [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zprofile.post.zsh" ]]; then
        builtin source "${HOME}/Library/Application Support/amazon-q/shell/zprofile.post.zsh"
        echo "..🛬 🪙 zprofile"
    fi
  # echo "\n<< end zprofile >>\n"
fi