format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$nats\
${env_var.PROFILE}\
${env_var.REGION}\
${env_var.CTX}\
${custom.cloud_context_break}\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$bun\
$c\
$cmake\
$cobol\
$cpp\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$maven\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$guix_shell\
$nix_shell\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$os\
$shell\
$character"""

[directory]
read_only = "🔒"

truncation_length = 0
truncate_to_repo = false
fish_style_pwd_dir_length = 0

[git_branch]
symbol = " "

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = '\$'
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_commit]
commit_hash_length = 8

[kubernetes]
format = '''[$symbol$context( \($namespace\))]($style)
'''
disabled = false

[env_var.PROFILE]
variable = "PROFILE"
symbol = "☁ "
format = "[$symbol$env_value]($style) "
style = "red"

[env_var.REGION]
variable = "REGION"
symbol = "🌎 "
format = "[$symbol$env_value]($style) "
style = "red"

[env_var.CTX]
variable = "CTX"
symbol = "⎈ "
format = "[$symbol$env_value]($style) "
style = "cyan"

[custom.cloud_context_break]
when = 'test -n "$PROFILE" -o -n "$REGION" -o -n "$CTX"'
command = "true"
format = "\n"

[aws]
symbol = "󰸏 "
style = "yellow"
disabled = false