# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Environment variables
[env]
TERM = "xterm-256color"
ALAC_DEBUG = "toml file"

[window]
# Window dimensions
dimensions = { columns = 120, lines = 35 }

# Window padding
padding = { x = 10, y = 10 }

# Window decorations
decorations = "full"

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title
dynamic_title = true

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling distance multiplier
multiplier = 3

# Font configuration
[font]
# Normal (roman) font face
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Bold font face
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# Italic font face
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Bold italic font face
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# Point size
size = 12.0

# Offset
[font.offset]
x = 0
y = 0

# Glyph offset
[font.glyph_offset]
x = 0
y = 0

# If `true`, bold text is drawn using the bright color variants
draw_bold_text_with_bright_colors = true

# Colors (Gruvbox Dark)
[colors]
# Default colors
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

# Normal colors
[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

# Bright colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[cursor]
# Cursor style
[cursor.style]
shape = "Block"
blinking = "On"

# Vi mode cursor style
vi_mode_style = "None"

# Cursor blinking interval in milliseconds
blink_interval = 750

# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused
unfocused_hollow = true

# Live config reload (changes require restart)
live_config_reload = true

# Shell
[shell]
program = "/usr/bin/zsh"
args = ["--login"]

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"
